Part10
yerlanmad/test-guru pull request #10
Opened 2020-12-20 06:30 UTC by yerlanmad

2020-12-20 09:15 UTC, VidgarVii requested changes

2020-12-20 09:15 UTC, VidgarVii commented on app/controllers/sessions_controller.rb
> +    session[:user_id] = nil
session.delete(:user_id)

2020-12-20 09:15 UTC, VidgarVii commented on app/models/user.rb
> +  EMAIL_FORMAT = /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i.freeze
лучше использовать готовый проверенный формат URI::MailTo::EMAIL_REGEXP

2020-12-20 09:15 UTC, VidgarVii commented on app/models/user.rb
> +  validate :validate_email_value
validates :email, format ....

2020-12-20 09:15 UTC, VidgarVii commented on app/controllers/application_controller.rb
> +  def flash_alert
1 Метод должен лежать в хелперах
2 Метод должен учитывать любой тип сообщения

2020-12-20 09:15 UTC, VidgarVii commented on app/controllers/sessions_controller.rb
> +      redirect_to cookies[:path] || root_path
во избежании проблем можно сразу path удалять

2020-12-20 09:15 UTC, VidgarVii commented on app/controllers/test_passages_controller.rb
> +    redirect_to root_path unless @test_passage.user_id == session[:user_id]
сомнительная проверка, ведь куки всегда можно подделать

2020-12-20 09:15 UTC, VidgarVii commented on app/controllers/application_controller.rb
> +    cookies[:email] = current_user&.email
а где эта кука будет использоваться?

2020-12-20 09:15 UTC, VidgarVii commented on app/controllers/application_controller.rb
> +      cookies[:path] = request&.path
1 сначала определяешь path
  затем редирект!
2 path - не совсем очевидное название для чего этот ключ нужен

2020-12-20 09:15 UTC, VidgarVii commented on app/views/layouts/application.html.erb
> +      <%= link_to 'Log out', logout_path %>
зачем видеть пользователю эту ссылку, если он еще не залогинен?

2020-12-20 09:15 UTC, VidgarVii commented on app/views/layouts/application.html.erb
> +      <%= link_to 'Log in', login_path %>
зачем видеть пользователю эти ссылки, если он уже залогинен?

2020-12-21 06:26 UTC, VidgarVii requested changes

2020-12-21 06:26 UTC, VidgarVii commented on app/controllers/sessions_controller.rb
> +      cookies.delete :requested_path
я уже писал, что редирект и рендер должен быть всегда последней строчкой в методе

2020-12-21 06:26 UTC, VidgarVii commented on app/controllers/sessions_controller.rb
> +      cookies.delete :requested_path
скобки! и проверь что возвращает метод delete

2020-12-21 06:26 UTC, VidgarVii commented on app/controllers/tests_controller.rb
> +    @user = User.find(session[:user_id])
т.е. если я поменяю в сессии юзер_ид я смогу прикинуться любым пользователем?

2020-12-21 06:26 UTC, VidgarVii commented on app/controllers/tests_controller.rb
>    before_action :find_user, only: :start
целый колбек для 1  экшена, слишком жирно будет. Получение данных должно быть явным. Колбек на 3 строчке скорей dry. А тут это не оправдано

2020-12-21 06:26 UTC, VidgarVii commented on app/helpers/application_helper.rb
> +  end
контент и тип для флэш обычно задается в контроллере. Хелперы помагают построить html

2020-12-21 06:26 UTC, VidgarVii commented on app/models/test.rb
> +  has_many :test_passages, dependent: :nullify
это для чего нам нарушать целостность данных?

2020-12-21 06:26 UTC, VidgarVii commented on app/views/layouts/application.html.erb
> +      <% end %>
хорошо бы это всё куда-нибудь в header утащить

2020-12-21 06:26 UTC, VidgarVii commented on app/views/sessions/_form.html.erb
> +    <%= content_tag :p, flash[:alert], class: 'flash alert'%>
потенциальный код для хелпера

2020-12-21 06:26 UTC, VidgarVii commented on config/routes.rb
> +  get :logout, to: 'sessions#destroy'
по соглашению rest за удаление ресурса отвечает метод delete

2020-12-22 01:01 UTC, yerlanmad commented on app/controllers/tests_controller.rb
> +    @user = User.find(session[:user_id])
Почему так можно делать здесь?
```
def current_user
  @current_user ||= User.find_by(id: session[:user_id]) if session[:user_id]
end
```

2020-12-22 11:18 UTC, yerlanmad commented on app/helpers/application_helper.rb
> +  end
Если честно, не совсем понял это задание. Зачем создавать хелпер для хелпер-метода
> 2. Создайте хэлпер для flash сообщений

2020-12-22 11:23 UTC, yerlanmad commented on app/views/sessions/_form.html.erb
> +    <%= content_tag :p, flash[:alert], class: 'flash alert'%>
что то я с этими хелперами запутался...

2020-12-22 16:09 UTC, VidgarVii requested changes

2020-12-22 16:09 UTC, VidgarVii commented on app/controllers/application_controller.rb
> +      redirect_to login_path, alert: helpers.flash_message(:alert)
данный хелпер для flash нужен только для использования в представлениях. Вызывать в контроллере хелперы представлений не имеет смысла.

2020-12-22 16:09 UTC, VidgarVii commented on app/helpers/application_helper.rb
> +    FLASH_MESSAGE[type]
этот хелпер должен принимать тип флеш сообщения  и возвращать стилизованный хтмл

2021-01-06 14:26 UTC, merged