Part12
yerlanmad/test-guru pull request #12
Opened 2021-02-01 18:17 UTC by yerlanmad

2021-02-01 18:45 UTC, VidgarVii requested changes

2021-02-01 18:45 UTC, VidgarVii commented on Gemfile
> +gem 'rails-i18n', '~> 6.0'
гем уже включён в рельсу. Подключать дополнительно ни чего не надо

2021-02-01 18:45 UTC, VidgarVii commented on app/controllers/application_controller.rb
>    end
глянь пример метода
https://www.rubydoc.info/github/plataformatec/devise/Devise/Controllers/Helpers:after_sign_in_path_for

2021-02-01 18:45 UTC, VidgarVii commented on app/controllers/application_controller.rb
> +  around_action :switch_locale
действие над совершать до вызова колбека

2021-02-01 18:45 UTC, VidgarVii commented on app/views/shared/_footer.ru.html.erb
> +  </p>
это всё тоже надо в локаль перетащить

2021-02-01 18:45 UTC, VidgarVii commented on app/views/test_passages/_full_result.en.html.erb
> +</p>
и это в локаль

2021-02-02 06:23 UTC, yerlanmad commented on app/controllers/application_controller.rb
>    end
> глянь пример метода
> https://www.rubydoc.info/github/plataformatec/devise/Devise/Controllers/Helpers:after_sign_in_path_for

Я его смотрел ранее, реализовал, как понял. Не правильно?

2021-02-02 10:01 UTC, VidgarVii commented on app/controllers/application_controller.rb
>    end
нужен stored_location_for. Гем пишет в куки, урл, ключ и пр. Эти данные нужны для корректной работы devise и редиректа пользователя после аутентификации

2021-02-06 09:37 UTC, merged