Part14
yerlanmad/test-guru pull request #14
Opened 2021-02-16 17:09 UTC by yerlanmad

2021-02-16 19:01 UTC, VidgarVii requested changes

2021-02-16 19:01 UTC, VidgarVii commented on Gemfile
> +gem 'dotenv-rails', groups: [:development, :test]
у тебя уже есть такая группа https://github.com/yerlanmad/test-guru/blob/72afd55d22aefae1dc8d5d9c1e385dc990339e0c/Gemfile#L50
лучше туда складывать гемы для этой группы

2021-02-16 19:01 UTC, VidgarVii commented on app/controllers/test_passages_controller.rb
> +    @gist = GistQuestionService.new(@question)
конструктор как правило возвращает экземпляр текущего класса. В данном случаи это точно не гист

2021-02-16 19:01 UTC, VidgarVii commented on app/controllers/test_passages_controller.rb
> +    flash_options = if (200..299).include?(result.status)
1 удовлетворительным результатом будет наличие ссылки на гист.
2 эту логику надо инкапсулировать в сервис

2021-02-16 19:01 UTC, VidgarVii commented on app/controllers/test_passages_controller.rb
> +  end
Gist у тебя целая модель. Согласно rails соглашению для него правильней будет создать отдельный контроллер. Я экшен для создания гиста соответственно будет create

2021-02-16 19:01 UTC, VidgarVii commented on app/helpers/gists_helper.rb
> +  end
1 название метода не согласуется с его реализацией
2 есть готовое решение https://apidock.com/rails/ActionView/Helpers/TextHelper/truncate

2021-02-16 19:01 UTC, VidgarVii commented on app/services/gist_question_service.rb
> +  def initialize(question, client: nil)
можно просто (question, client:)

2021-02-16 19:01 UTC, VidgarVii commented on app/services/gist_question_service.rb
> +  end
[
...
].join('\n')

2021-02-27 16:06 UTC, yerlanmad commented on app/services/gist_question_service.rb
> +  def initialize(question, client: nil)
![image](https://user-images.githubusercontent.com/43934798/109392733-ff6e7500-7947-11eb-887c-cf09aed398af.png)

2021-03-06 09:34 UTC, merged