part 4 tasks
yerlanmad/test-guru pull request #4
Opened 2020-10-15 20:30 UTC by yerlanmad

db/seed.rb added
#accepted_tests method added to User model
::test_names method added to Test model

additionally TestHistory model created

2020-10-16 03:45 UTC, max-underthesun reviewed
запросы (в методах) будет правильно решить через джойн таблиц
то как ты делаешь - это "решение в лоб"
оно работает, но оно скажем мягко "не оптимальное"

рельсы многие запросы могут сами оптимизировать в итоге и, к примеру, составить автоматически из двух запросов один, но полагаться на это не стоит
в реальной жизни такие запросы, как у тебя получились, писать не нужно

плюс мы сейчас пытаемся разобраться с тем, как работают ассоциации в рельсах, чтобы в дальнейшем было понимание того "что же они делают" и "как это работает", так вот рельсы точно не пишут такие запросы, конечно же все оптимизировано
посмотри предыдущее задание - там были (в части по скуль запросам) селекты с джойнами таблиц

здесь нужно в обоих методах решить все с помощью `joins` и `where` (в одно обращение к базе, один запрос)
пострайся разобраться - это важно и полезно
если будут вопросы - пиши в слак

2020-10-16 03:45 UTC, max-underthesun commented on db/seeds.rb
> +  test = Test.create(title: "Test_#{id}", level: rand(3), category_id: category.id)
лучше использовать `create!` - метод бросит исключение, если запись не создастся
сразу будет видно, если что-то пошло не так

2020-10-16 03:45 UTC, max-underthesun commented on db/seeds.rb
> +def create_test(id, category)
рекомендуется создавать записи "с группировкой по таблицам"
т.е. сначала создаем все категории, потом все тесты, потом все вопросы, так проще найти нужную информацию в файле, в твоем варианте приходится искать и разбираться где и что создавалось

2020-10-16 03:45 UTC, max-underthesun commented on db/seeds.rb
> +def create_test(id, category)
для создания можно передавать в метод `create` массив хэшей:
```ruby
categories = Category.create!([
  { title: 'Rails' },
  ...
  { title: 'JAVA' }
])
```
далее в таком стиле:
```ruby
tests = Test.create!([
  { title: ..., level: 0, category_id: categories[0].id },
  { title: ..., level: 1, category_id: categories[1].id },
  ...
])
```

2020-10-24 09:07 UTC, max-underthesun commented on app/models/test.rb
> +    Test.joins(:category).where("categories.category = :category", category: category).order(title: :desc).pluck(:title)
с ассоциациями ты поторопился, это будет чуть дальше в курсе
в этом задании нужно все решать через SQL, с помощью  ActiveRecord queries, но без использования ассоциаций
суть урока - понять какую работу делает за нас `ActiveRecord` и для этого нужно здесь выполнить ее самому
давай сделаем следующее:
- избавься от ассоциаций (оставь связи только на уровне БД, но не на уровне моделей)
- перепиши методы в моделях `User`, `Test` без использования ассоциаций

2020-10-24 09:07 UTC, max-underthesun commented on app/models/user.rb
> +    TestHistory.joins(:test, :user).where("users.id = :id and level = :level", id: self.id, level: level).pluck("tests.title")
тут несколько ошибок, кроме использвоания ассоциаций

ТЗ: "возвращает список всех Тестов, которые проходит или когда-либо проходил Пользователь на этом уровне сложности"
- метод должен возвращать "список всех тестов", т.е. коллекцию объектов
твой возвращает только имена ("тайтлы"), т.е. только один атрибут объекта, вместо целого объекта
- ждойнить таблицу `users` нет смысла, поле `user_id` есть в таблице `test_histrories`
- вернуться дожлжны объекты класса `Test`, значит обращаться необходимо к этой модели, а не к `TestHistory`

и следующая рекомендация
условия на таблицы лучше накладывать через хэши - их проще читать и редактировать
в таком стиле:
```ruby
.where(level: level, users: { id: id })
```
(но запрос нужно переписать с учетом предыдущих комментариев и этот `where` поменятеся)

2020-10-26 17:05 UTC, VidgarVii requested changes

2020-10-26 17:05 UTC, VidgarVii commented on db/seeds.rb
> +
Было бы просто замечательно, если бы мы сиды защитили от повторных запусков. Очень хорошей практикой является проверка наличие дынных. Пример 

```
unless Category.exists? && Test.....
  code...
end
```
Это предотвратит создание 6 категорий, если случайно будет запущен db:seeds 2 раза. Что бывает на практике довольно часто при разработке сидов.

2020-10-26 17:05 UTC, VidgarVii commented on db/seeds.rb
> +tests.each.with_index(1) do |tst, i|
не стесняйся писать имена полностью, в программирование сокращения не приветствуются. Тем более 1 буква погоду не сделает =) tst vs test

2020-10-26 17:05 UTC, VidgarVii commented on db/seeds.rb
> +questions.each.with_index(1) do |que, i|
que vs question

2020-10-26 17:05 UTC, VidgarVii commented on db/seeds.rb
> +answers = []
коллекция answers в сидах никак не используется. Можно её не собирать. строка 28

2020-10-26 17:05 UTC, VidgarVii commented on db/seeds.rb
> +  Answer.where(question_id: que.id).sample.update(correct: true)
1. Не критично. Для записи булевого значения в поле correct, что бы не тратить время на лишний запрос в БД для получение ответа, можно применить маленький хак. 

Answer.create!(body:"Answer_#{i}-#{n}", question_id: que.id, **correct: (n == 1)**)

Да верный ответ теперь будет только первый, а не рандомный. Но я не думаю, что это прям сильно поломает бизнес логику) Ведь сиды создают в основном для разработки. 

2. .update!()

2020-10-26 17:05 UTC, VidgarVii commented on test/fixtures/test_histories.yml
> +# Read about fixtures at https://api.rubyonrails.org/classes/ActiveRecord/FixtureSet.html
можно смело удалить этот странный файл. Тесты, фикстуры, фабрики будут потом по курсу. А ПР должен быть чист как попа младенца

2020-10-26 17:05 UTC, VidgarVii commented on test/models/test_history_test.rb
> +require 'test_helper'
аналогично файл, на удаление

2020-10-26 17:05 UTC, VidgarVii commented on app/models/user.rb
> +    Test.joins("INNER JOIN test_histories ON test_histories.test_id = tests.id").where(level: level, test_histories: { user_id: self.id }).distinct
1. Если что-то не влезает в 120 символов. Смело переноси вызов методов на другую строку. Читаться будет на много лучше и как минимум хорошая стилистическая практика. Советую пока не закрывать [эту страничку](https://github.com/rubocop-hq/ruby-style-guide) =) 
```
    Test
      .joins("INNER JOIN test_histories ON test_histories.test_id = tests.id")
      .where(level: level, test_histories: { user_id: self.id })
      .distinct
```
2. INNER можно не писать, он подразумевается по умолчанию
3. По названию метода не очень очевидно почему он должен принимать какой-то уровень. А так же accepted дает понять, что тест был пройден. Хотя по условию задачи сказано `возвращает список всех Тестов, которые проходит или когда-либо проходил` Лучше дать более подходящее название метода
```
passed_tests_by_level(level)
history_tests_by_level(level)
passed_tests_by_level_difficulty(level)
...
```
4. distinct - он точно нужен?

2020-10-26 17:05 UTC, VidgarVii commented on app/models/test.rb
> +    Test.joins("INNER JOIN categories ON tests.category_id = categories.id").where(categories: { category: category }).order(title: :desc).pluck(:title)
так как мы уже работаем в контексте класса Test. Test в методе можно не писать. Т.е. код можно начинать сразу с `joins("INNE...`

2020-10-27 02:23 UTC, merged