Part6
yerlanmad/test-guru pull request #6
Opened 2020-11-24 14:27 UTC by yerlanmad

2020-11-24 16:10 UTC, VidgarVii requested changes

2020-11-24 16:10 UTC, VidgarVii commented on app/models/test.rb
> +  }
проще, декларативней, читабельней будет определить 3 скоупа.
```
scope :easy, -> { where(level: 0..1) }
scope :medium, -> { where(level: 2..4) }
...
```

2020-11-24 16:10 UTC, VidgarVii commented on app/models/test.rb
> +      none
scope всегда должен возвращать ActiveRecord_Relation

2020-11-24 16:10 UTC, VidgarVii commented on app/models/answer.rb
> +    errors.add(:answers, "too much") if question.answers.count >= 4
У одного Вопроса может быть от 1-го до 4-х ответов.
а не 3х)

2020-11-24 16:10 UTC, VidgarVii commented on app/models/answer.rb
> +  validate :validate_belong_count
нам не нужно проверять кол--во ответов при каждой транзакции ответа. Следует указать, когда мы должны обращаться к данной валидации

2020-11-25 15:16 UTC, yerlanmad commented on app/models/answer.rb
> +    errors.add(:answers, "too much") if question.answers.count >= 4
Здесь все верно. Если сделать question.answers.count > 4, то создается до 5 ответов.

2020-11-25 15:18 UTC, yerlanmad commented on app/models/test.rb
> +      none
по идее этот момент был учтен)
`2.7.0 :021 > Test.none
 => #<ActiveRecord::Relation []> `

2020-11-25 17:06 UTC, VidgarVii approved these changes

2020-11-28 07:37 UTC, merged